### ISSUE TITLE
Can not compile SageMaker examples

### ISSUE THREAD

**Issue by Jeffwan** [aws-samples/eks-kubeflow-workshop#1]
Trying our your Kubeflow/SageMaker notebook in your workshop and received a pipeline compile error.  

![image](https://user-images.githubusercontent.com/4739316/66772250-1e628900-ee71-11e9-92f0-afceb992313a.png)

**Comment by Jeffwan** [comment]
This is reported by user and the problem is kubeflow pipeline has some breaking changes on parameters but we always install latest KFP pipeline which is not compatible. 

Short term. use lower kfp version
```
!pip install https://storage.googleapis.com/ml-pipeline/release/0.1.29/kfp.tar.gz --upgrade
```

Long term, update examples and make sure it leverages latest features of KFP.

**Comment by PatrickXYS** [comment]
Will check on the [SageMaker example](https://github.com/aws-samples/eks-kubeflow-workshop/blob/01438d181f502504056eac89bfc0eb091733e9a8/notebooks/05_Kubeflow_Pipeline/05_04_Pipeline_SageMaker.ipynb) and file a PR to make it leverage the latest features of KFP.

**Comment by PatrickXYS** [comment]
And the master example of [SageMaker Kubeflow Pipeline](https://github.com/kubeflow/pipelines/tree/master/samples/contrib/aws-samples/mnist-kmeans-sagemaker), will try to use [master yaml file](https://github.com/kubeflow/pipelines/tree/master/components/aws/sagemaker). After so, will try to use latest version 2.05 of kfp to make it compatible.

**Comment by PatrickXYS** [comment]
Potential SageMaker example issues with users: [1st](https://github.com/kubeflow/pipelines/issues/1401) and [2nd](https://github.com/kubeflow/pipelines/issues/1642). But the issue description is not that informative. Will talk with users if necessary.

**Comment by Jeffwan** [comment]
Let's not put time on this one. I will ask SM team to fix Op issue and we can concentrate on others.

**Comment by PatrickXYS** [comment]
Since the updated SageMaker example has been merged, let's close this issue.
