### ISSUE TITLE
Make it easy to create ECR and S3 in fairing introduction

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/eks-kubeflow-workshop#12]
Creating ECR repository from notebook interface rather than hopping back and forth between AWS Console will simplify Fairing introduction notebook

**Comment by dalbhanj** [comment]
!aws ecr create-repository --repository-name fairing-job --region=$REGION

**Comment by Jeffwan** [comment]
Sounds good. I also add some instructions for `us-east-1` which is kind of special.
