### ISSUE TITLE
No module named 'kfp.aws'

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/eks-kubeflow-workshop#14]
I'm getting this error when I run Sagemaker pipeline notebook

Here is the error. 
--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-38c0def86066> in <module>
      2 from kfp import components
      3 from kfp import dsl
----> 4 from kfp.aws import use_aws_secret

ModuleNotFoundError: No module named 'kfp.aws'

Looks like we need to add prerequisites to install kfp

**Comment by Jeffwan** [comment]
Yes. Please restart the kernel before moving to next blocks. both 05_01 and 05_04 will be used for workshop. 05_01 will cover installation as well.
