### ISSUE TITLE
Update Fairing instructions

### ISSUE THREAD

**Issue by Jeffwan** [aws-samples/eks-kubeflow-workshop#35]
https://github.com/aws-samples/eks-kubeflow-workshop/tree/master/notebooks/02_Fairing

There're a few issues in 0.7 and that's the reason I wrote a separate guidance for fairing. 
A few things have been changed in 1.0. 

1. awscli have been added to notebook. However, docker client is not yet, which means dockerBuilder still won't work. We need to address this problem in our image I think. 

2. `istio-injection` probably get updated, I think we don't need this anymore. need some verification

3. ECR permission -> Consider to ask user to use enable IAM for service account.  Update policy for `kf-user-${cluster-name}`. Fairing pod also need to use `default-editor`

**Comment by PatrickXYS** [comment]
1. `Docker client` hasn't been added, thus, we have to keep the image or address the problem in our later image.
2. We're able to get rid of `istio-injection` and I tested all the Fairing examples.
3. I will add instructions to ask users to use enable IAM for SA.

**Comment by PatrickXYS** [comment]
Besides that, I confirmed that `gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-cpu:1.0.0` has installed `docker client` and `awscli`. But if we want to utilize this image, we have to modify Tensorflow codes, some of the APIs have already been deprecated and disabled.

**Comment by Jeffwan** [comment]
@PatrickXYS Interesting, I didn't see the PR to install Docker client. Unless base image has docker client

**Comment by PatrickXYS** [comment]
My bad, double-checked and there's no `docker`.  We should build our own eks-kubeflow-workshop image to handle the `no docker client` issue.

**Comment by Jeffwan** [comment]
PR has been merged and this can be closed
