### ISSUE TITLE
Remove redundant code snippets in 05_03_Pipeline_Mnist notebook

### ISSUE THREAD

**Issue by PatrickXYS** [aws-samples/eks-kubeflow-workshop#53]
Previously we have a workaround for enabling `pipeline-runner` service account to create resource "virtualservices" in API group "networking.istio.io" in the namespace "kubeflow":

![image](https://user-images.githubusercontent.com/23116624/79706092-e8adbb00-826c-11ea-9185-90cd825f62bb.png)

Per [upstream PR](https://github.com/kubeflow/manifests/pull/1060) merged, we'll remove this instruction.

**Comment by Jeffwan** [comment]
@PatrickXYS v1.0.2 has been released. We can do some clean up and cut a v1.0.2 release for this repo

**Comment by PatrickXYS** [comment]
Sure, I'll test v1.0.2 compatibility with eks-kubeflow-workshop this week. And meanwhile clean up redundant code snippets / instruction, etc.

**Comment by Jeffwan** [comment]
@PatrickXYS Excellent!
