### ISSUE TITLE
EKS MLflow Server Artifact Error

### ISSUE THREAD

**Issue by JMV1072** [aws-samples/eks-kubeflow-workshop#57]
I'm trying to create a docker image to run mlflow on an eks pod. it is able to deploy and store info to my postgres backend, but I get the following error when attempting to save my artifacts to s3:

`An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity`

I'm setting the env variables in my dockerfile. Why would this happen? I've tested it locally also and it works. Just not when deployed to eks.

**Comment by PatrickXYS** [comment]
Hi, have you attached the S3FullAccess Policy to your nodeintancerole?
