### ISSUE TITLE
Need step to create ECR repository

### ISSUE THREAD

**Issue by otterley** [aws-samples/eks-kubeflow-workshop#6]
ECR repository `fairing-job` needs to be created before trying to push to it.  A step in the Jupyter notebook should be added.

**Comment by Jeffwan** [comment]
@otterley Thanks. This is good. I think one more thing I can improve this is add support in fairing project to check `fairing-job` before it push images. If this is not found, we can have some initialization. 

I will file PR to workshop for short term solution and PR to kubeflow/fairing for long term
