### ISSUE TITLE
Error: found errors when executing run: <run_id>. Click Details for more information.

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/eks-kubeflow-workshop#70]
**Notebook**
Which notebook you have problem with? 05_04_Pipeline_SageMaker.ipynb

**Describe the bug**
I was getting an error while executing kfp run with Sagemaker notebook. Its possible that the latest kfp sdk has breaking changes that affects this run

**Expected behavior**
kfp pipeline should run Sagemaker jobs as defined in the notebook

**Screenshots**
![image](https://user-images.githubusercontent.com/19981010/89332829-0a874e00-d662-11ea-8cf1-8e2667df72b8.png)

**Environment (please complete the following information):**
 - EKS version: 1.14
 - Kubeflow version: kfctl version
kfctl v1.0.1-0-gf3edb9b
 - eks-kubeflow-workshop version: latest

**Comment by Jeffwan** [comment]
PR merged. this should be resolved
