### ISSUE TITLE
05_02_Pipeline_lightweight missing import for kfp components

### ISSUE THREAD

**Issue by mshapirov** [aws-samples/eks-kubeflow-workshop#9]
Step:
add_op = comp.func_to_container_op(add, base_image='python:3.6.8')

Fails with unknown identifier for comp. 

Can be fixed by adding import to the function definition step:
```
#Define a Python function
import kfp
from kfp import components
```

**Comment by Jeffwan** [comment]
Ah.. I have similar issues yesterday and I probably forget to import the libraries. Thanks. I will file a PR  to address this issue
